### ISSUE TITLE
改变数据源时如何进行重绘？

### ISSUE THREAD

**Issue by huhai0403** [holanlan/b2wordcloud#2]
`var wordCloud01 = new B2wordcloud(document.getElementById('wordCloud01'), {
        list: dataArr[dataIndex01],
        tooltip: {
          show: true,
          formatter: function(item) {
            return '<div>' + item[0] + '</div>' + '<div>' + item[1] + '</div>'
          }
        }
      });`
当需要重绘时，我修改`dataArr[dataIndex01]`的值，但是没有触发重绘

**Comment by holanlan** [comment]
目前没有监听options更新重绘的逻辑，重新执行一次初始化即可
