### ISSUE TITLE
移动端文字模糊

### ISSUE THREAD

**Issue by ysysyg** [holanlan/b2wordcloud#3]
![image](https://user-images.githubusercontent.com/20873838/91279857-9e0ef300-e7b8-11ea-8f0c-fb733861a0cc.png)

在 hi-dpi 设备上文字模糊

options 配置如下👇
`const baseOptions = {
  list: newList,
  maxRotation: 0,
  minRotation: 0,
  color: Purple_Colors,
  shape: 'circle',
  drawOutOfBound: false,
  shrinkToFit: true,
  clearCanvas: '#fff',
  gridSize: 9
}`

**Comment by holanlan** [comment]
> ![image](https://user-images.githubusercontent.com/20873838/91279857-9e0ef300-e7b8-11ea-8f0c-fb733861a0cc.png)
> 
> 在 hi-dpi 设备上文字模糊
> 
> options 配置如下👇
> `const baseOptions = { list: newList, maxRotation: 0, minRotation: 0, color: Purple_Colors, shape: 'circle', drawOutOfBound: false, shrinkToFit: true, clearCanvas: '#fff', gridSize: 9 }`


2.0.0版本已经解决
