### ISSUE TITLE
您好，关于文字旋转部分，无法旋转，是将文字旋转功能取消了吗？

### ISSUE THREAD

**Issue by lian-store** [holanlan/b2wordcloud#4]

**Comment by holanlan** [comment]
指的是哪个api？

**Comment by lian-store** [comment]
> 指的是哪个api？
https://github.com/timdream/wordcloud2.js/blob/gh-pages/API.md
原本的wordclound2.js中有个rotateRatio，来设置文字是否旋转，但是我在这里使用了是没有效果的

**Comment by holanlan** [comment]
> > 指的是哪个api？
> > https://github.com/timdream/wordcloud2.js/blob/gh-pages/API.md
> > 原本的wordclound2.js中有个rotateRatio，来设置文字是否旋转，但是我在这里使用了是没有效果的

这是个bug，已经修复，可以更新一下npm包

**Comment by lian-store** [comment]
> > > 指的是哪个api？
> > > https://github.com/timdream/wordcloud2.js/blob/gh-pages/API.md
> > > 原本的wordclound2.js中有个rotateRatio，来设置文字是否旋转，但是我在这里使用了是没有效果的
> 
> 这是个bug，已经修复，可以更新一下npm包

OK

**Comment by holanlan** [comment]
问题已经解决，issue关闭
